spring.application.name=order-management
server.port=${PORT:8080}

# hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Scheduler
scheduler.interval=60000

# driver comum aos dois bancos
spring.datasource.driver-class-name=org.postgresql.Driver